const accessRights = {
  DASHBOARD_VIEW: 12,

  CAMPAIGNS_VIEW: 58,
  CAMPAIGNS_ADD: 59,
  CLIENTS_LIST_VIEW: 60,
  CLIENTS_LIST_ONBOARDING: 61,
  
  PAYEES_LIST_VIEW: 2323, 
  PAYEES_LIST_DOWNLOAD:2324,
  // CLIENTS_LIST_ADD: 60,
  // CLIENTS_LIST_UPDATE: 61,
  // CLIENTS_LIST_DELETE: 62,

  USERS_LIST_ADD: 62,
  USERS_LIST_UPDATE: 63,
  USERS_LIST_DELETE: 64,

  USERS_LIST_VIEW: 65,

  USER_CLIENT_PERMISSION: 63,

  USERS_LIST_LOCK: 66,
  USERS_LIST_UNLOCK: 67,
  // USERS_LIST_DELETE: 66,
  USERS_ROLES_ADD: 68,
  USERS_ROLES_EDIT: 69,
  USERS_ROLES_VIEW: 70,
  REPORTS_VIEW: 71,
  REPORTS_DOWNLOAD: 72,
  REPORTS_SUBSCRIBE: 73,

  REPORTS_DYNAMIC_EDIT: 113,
  REPORTS_DYNAMIC_CREATE: 112,
  REPORTS_DYNAMIC_DELETE: 114,
  REPORTS_DYNAMIC_DOWNLOAD: 115,
  REPORTS_DYNAMIC_SUBSCRIBE: 116,
  
  CARDS_CLIENTS_LIST: 2325,
  CARDS_CLIENTS_LIST_DOWNLOAD: 2326
};

export default accessRights;