export const Steppers = [
  'CLIENT PROFILE SETUP',
  'CONFIGURE CLIENT PORTAL',
  'CLIENT PROFILE DETAILS',
  'PAYMENT INFORMATION',
  'FILE SETTINGS',
  'REMITTANCE SETUP',
];

export const USBankStepper = [
    "CLIENT PROFILE SETUP",
    "CONFIGURE CLIENT PORTAL",
    "CLIENT PROFILE DETAILS",
    "PAYMENT INFORMATION",
    "SETTINGS",
    "REMITTANCE SETUP",
]
